// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnyheapfzuirppczbuaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZueWhlYXBmenVpcnBwY3pidWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTQ3ODUsImV4cCI6MjA3Mzk3MDc4NX0.docZfdUqIc2coA6mgCNZyny37v5cIs15X9GXyAtmVgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});